### ISSUE TITLE
[Question]: Are they plans to use a more FP approach?

### ISSUE THREAD

**Issue by taverasmisael** [tomi/fromfrom#28]
I don't know how to formulate the question correctly or if it makes sense.

I love the library, but the first thing that came to mind was if it were possible to use function composition with it. Export the transforms as standalone functions waiting for an Iterator and be able to compose transformations. Is this out of the scope?

### Example (comopse):

```typescript
// from the main example
import { compose, filter, sortBy } from 'fromfrom/transforms';

const activeSortedByName = compose(
  sortByDescending(user => user.age),
  filter(user => user.active)
);

const result = activeSortedByName(users).toArray();
```

### Example (pipe):

```typescript
// from the main example
import { pipe, filter, sortBy, toArray } from 'fromfrom/transforms';

const activeSortedByName = pipe(
  filter(user => user.active),
  sortByDescending(user => user.age),
  toArray
);

const result = activeSortedByName(users);
```

**Comment by tomi** [comment]
Hi and thank you for your question. See my reply in issue #30
