### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by joshuaalpuerto** [tomi/fromfrom#29]
Hi there,

This library looks interesting and helpful! 

I just want to know how chaining works here regarding with the performance.  Since chaining  creates a temporary array  w/c affects performance. That is why  using  **transducer** on a massive list is better.

Any thoughts?

**Comment by tomi** [comment]
Hi and thank you for your question.

The library does not work the same way as native `Array` does. In other words, it does not (always) create temporary arrays. Please see the "Deferred execution and lazy evaluation" section in the [announcement blog post](https://www.futurice.com/blog/announcing-fromfrom/) for more detailed explanation.

**Comment by joshuaalpuerto** [comment]
That's awesome!
