### ISSUE TITLE
Chosen TSlib is es2015

### ISSUE THREAD

**Issue by jfet97** [tomi/fromfrom#32]
Are there any particular reasons why the development version of ts is set to es2015 instead of es2018?

**Comment by jfet97** [comment]
Because some improvements would be possible, on the development side.
For example, into _ObjectIterable.ts_ the for..in cycle which could be substituted with:
```ts
for (const keyValuePair in Object.entries(object)) {
    yield keyValuePair as any;
}
```
or:
```ts
Object.entries(object).forEach( keyValuePair => {
    yield keyValuePair as any;
})
```

**Comment by jfet97** [comment]
@tomi

**Comment by tomi** [comment]
Hi @jfet97 and thank you for your question. The reason for targeting es2015 is that it's the lowest version that is possible to be targeted. fromfrom uses iteration protocols, which became available in es2015. I don't see many benefits of using a newer version.

Now when it comes to the example you mentioned, I think it depends if the way you mention is actually better than the for..of that is used now. Is using `Object.entries` more readable? Definitely. Is it less code? A little. Is it more performant? I don't know, that would have to be measured. At least it uses more memory as `Object.entries` creates a new intermediary array.

**Comment by jfet97** [comment]
target version !== development version
