### ISSUE TITLE
Doc: Add usage example for sequence methods

### ISSUE THREAD

**Issue by tomi** [tomi/fromfrom#49]
Not all methods of `Sequence` have a usage example [in the documentation](https://tomi.github.io/fromfrom/api/classes/sequence.html). We should add usage examples with an `@example` JSDoc annotation to all methods. This way they end up in the generated API documentation automatically.

**Comment by buoyantair** [comment]
@tomi I would love to take this up!

**Comment by hollannikas** [comment]
I'll have a look at this, if that's okay :)
